[package]
name = "luma"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.31"
rand = "0.8"
winit = "0.28"
wgpu = "0.15"
pollster = "0.3"
